Update lint script

diff --git a/.github/workflows/lint_mps.yml b/.github/workflows/lint_mps.yml
--- a/.github/workflows/lint_mps.yml
+++ b/.github/workflows/lint_mps.yml
@@ -14,39 +14,86 @@ concurrency:
 
 jobs:
   lintrunner-mps:
-    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
-    with:
-      runner: macos-executorch
-      fetch-depth: 0
-      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
-      script: |
-        # The generic Linux job chooses to use base env, not the one setup by the image
-        CONDA_ENV=$(conda env list --json | jq -r ".envs | .[-1]")
-        conda activate "${CONDA_ENV}"
+    runs-on: macos-executorch
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: 'true'
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+          cache: pip
+      - name: Extract the list of models to test
+        id: lint-mps
+        run: |
+          set -eux
+          source .ci/scripts/utils.sh
+          # This is a simple Python script but as it tries to import executorch.examples.models,
+          # it requires a whole bunch of ExecuTorch dependencies on the Docker image
+          install_pip_dependencies
+          install_executorch
+          CONDA_ENV=$(conda env list --json | jq -r ".envs | .[-1]")
+          conda activate "${CONDA_ENV}"
 
-        CACHE_DIRECTORY="/tmp/.lintbin"
-        # Try to recover the cached binaries
-        if [[ -d "${CACHE_DIRECTORY}" ]]; then
-          # It's ok to fail this as lintrunner init would download these binaries
-          # again if they do not exist
-          cp -r "${CACHE_DIRECTORY}" . || true
-        fi
+          CACHE_DIRECTORY="/tmp/.lintbin"
+          # Try to recover the cached binaries
+          if [[ -d "${CACHE_DIRECTORY}" ]]; then
+            # It's ok to fail this as lintrunner init would download these binaries
+            # again if they do not exist
+            cp -r "${CACHE_DIRECTORY}" . || true
+          fi
 
-        # This has already been cached in the docker image
-        lintrunner init 2> /dev/null
+          # This has already been cached in the docker image
+          lintrunner init 2> /dev/null
 
-        RC=0
-        # Run lintrunner on all files
-        if ! lintrunner --force-color --all-files --tee-json=lint.json 2> /dev/null; then
-          echo ""
-          echo -e "\e[1m\e[36mYou can reproduce these results locally by using \`lintrunner\`. (If you don't get the same results, run \'lintrunner init\' to update your local linter)\e[0m"
-          echo -e "\e[1m\e[36mSee https://github.com/pytorch/pytorch/wiki/lintrunner for setup instructions.\e[0m"
-          RC=1
-        fi
+          RC=0
+          # Run lintrunner on all files
+          if ! lintrunner --force-color --all-files --tee-json=lint.json 2> /dev/null; then
+            echo ""
+            echo -e "\e[1m\e[36mYou can reproduce these results locally by using \`lintrunner\`. (If you don't get the same results, run \'lintrunner init\' to update your local linter)\e[0m"
+            echo -e "\e[1m\e[36mSee https://github.com/pytorch/pytorch/wiki/lintrunner for setup instructions.\e[0m"
+            RC=1
+          fi
 
-        # Use jq to massage the JSON lint output into GitHub Actions workflow commands.
-        jq --raw-output \
-          '"::\(if .severity == "advice" or .severity == "disabled" then "warning" else .severity end) file=\(.path),line=\(.line),col=\(.char),title=\(.code) \(.name)::" + (.description | gsub("\\n"; "%0A"))' \
-          lint.json || true
+          # Use jq to massage the JSON lint output into GitHub Actions workflow commands.
+          jq --raw-output \
+            '"::\(if .severity == "advice" or .severity == "disabled" then "warning" else .severity end) file=\(.path),line=\(.line),col=\(.char),title=\(.code) \(.name)::" + (.description | gsub("\\n"; "%0A"))' \
+            lint.json || true
 
-        exit $RC
+          exit $RC
+
+    # with:
+    #   runner: macos-executorch
+    #   fetch-depth: 0
+    #   ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
+    #   script: |
+    #     # The generic Linux job chooses to use base env, not the one setup by the image
+    #     CONDA_ENV=$(conda env list --json | jq -r ".envs | .[-1]")
+    #     conda activate "${CONDA_ENV}"
+
+    #     CACHE_DIRECTORY="/tmp/.lintbin"
+    #     # Try to recover the cached binaries
+    #     if [[ -d "${CACHE_DIRECTORY}" ]]; then
+    #       # It's ok to fail this as lintrunner init would download these binaries
+    #       # again if they do not exist
+    #       cp -r "${CACHE_DIRECTORY}" . || true
+    #     fi
+
+    #     # This has already been cached in the docker image
+    #     lintrunner init 2> /dev/null
+
+    #     RC=0
+    #     # Run lintrunner on all files
+    #     if ! lintrunner --force-color --all-files --tee-json=lint.json 2> /dev/null; then
+    #       echo ""
+    #       echo -e "\e[1m\e[36mYou can reproduce these results locally by using \`lintrunner\`. (If you don't get the same results, run \'lintrunner init\' to update your local linter)\e[0m"
+    #       echo -e "\e[1m\e[36mSee https://github.com/pytorch/pytorch/wiki/lintrunner for setup instructions.\e[0m"
+    #       RC=1
+    #     fi
+
+    #     # Use jq to massage the JSON lint output into GitHub Actions workflow commands.
+    #     jq --raw-output \
+    #       '"::\(if .severity == "advice" or .severity == "disabled" then "warning" else .severity end) file=\(.path),line=\(.line),col=\(.char),title=\(.code) \(.name)::" + (.description | gsub("\\n"; "%0A"))' \
+    #       lint.json || true
+
+    #     exit $RC
